#%RAML 1.0
title: Inventory Update
version: v1.0
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost

documentation:
  - title: Inventory update APIs
    content: <b>Provides various schemes for creating, updating and deleting instances, holdings records and items in Inventory storage</b>

types:
  instance: !include instance.json
  inventory-record-set: !include inventoryRecordSet.json

resourceTypes:
  collection-item: !include raml-util/rtypes/item-collection.raml

traits:
  language: !include raml-util/traits/language.raml

/instance-storage-match:
  /instances:
    displayName: Instance create or update by matchkey (being deprecated)
    put:

/inventory-upsert-hrid:
  displayName: Create, update, delete instance with holdings and items, based on instance HRID
  put:
  delete:

/shared-inventory-upsert-matchkey:
  displayName: Create, update, "delete" instance with holdings and items, based on instance match key
  put:
  delete:
