#%RAML 1.0
title: Inventory Update
version: v1.0
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost

documentation:
  - title: Inventory update APIs
    content: <b>Provides various schemes for creating, updating and deleting instances, holdings records and items in Inventory storage</b>

types:
  instance: !include instance.json
  inventory-record-set: !include inventoryRecordSet.json
  hrid-deletion: !include hrid-deletion.json
  shared-index-deletion: !include shared-index-deletion.json

resourceTypes:
  collection-item: !include raml-util/rtypes/item-collection.raml

traits:
  language: !include raml-util/traits/language.raml

/instance-storage-match:
  displayName: Instance create or update by match key (being deprecated)
  /instances:
    put:
        body:
            application/json:
                type: instance

/inventory-upsert-hrid:
  displayName: Create, update, delete instance with holdings and items, based on incoming HRIDs on all three record types
  put:
    body:
        application/json:
            type: inventory-record-set
  delete:
    body:
        application/json:
            type: hrid-deletion

/shared-inventory-upsert-matchkey:
  displayName: Create, update, "delete" instance, replace its holdings and items, based on instance match key
  put:
    body:
        application/json:
            type: inventory-record-set
  delete:
    body:
        application/json:
            type: shared-index-deletion
