#%RAML 1.0
title: Inventory Update
version: v1.0
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost

documentation:
  - title: Inventory update APIs
    content: <b>Provides various schemes for creating, updating and deleting instances, holdings records and items in Inventory storage</b>

types:
  instance: !include instance.json
  inventory-record-set: !include inventory-record-set.json
  inventory-record-set-with-hrids: !include inventory-record-set-with-hrids.json
  inventory-record-sets-with-hrids: !include inventory-record-sets-with-hrids.json
  holdings-record: !include holdings-record.json
  holdings-record-with-hrid: !include holdings-record-with-hrid.json
  item: !include item.json
  item-with-hrid: !include item-with-hrid.json
  hrid-deletion: !include hrid-deletion.json
  shared-index-deletion: !include shared-index-deletion.json
  upsert-response-200: !include upsert-response-200.json
  upsert-response-207: !include upsert-response-207.json
  batch-upsert-response-207: !include batch-upsert-response-207.json
  error-response: !include error-response.json
  metrics: !include metrics.json
  get-recordset-response: !include get-recordset-response.json

resourceTypes:
  collection-item: !include raml-util/rtypes/item-collection.raml

traits:
  language: !include raml-util/traits/language.raml


/inventory-upsert-hrid:
  displayName: Create, update, delete instance with holdings and items, based on incoming HRIDs on all three record types
  put:
    body:
        application/json:
            type: inventory-record-set-with-hrids
    responses:
        200:
            description: "Inventory recordset successfully created or updated by HRIDs."
            body:
                application/json:
                    type: upsert-response-200
        207:
            description: "Partially successful update of record set. Errors listed in response."
            body:
                application/json
                    type: upsert-response-207
        422:
            description: "One or more validation errors found in incoming record set. No updates performed."
            body:
                application/json:
                    type: error-response
        400:
            description: "Bad request, for example: empty request body, non-JSON or invalid JSON in request body or JSON not recognized as an inventory record set"
            body:
                application/json:
                    type: error-response
        500:
            description: "Internal errors in the module itself or in the modules that it uses."
            body:
                application/json:
                    type: error-response

  delete:
    body:
        application/json:
            type: hrid-deletion
    responses:
        200:
            description: "Record set was successfully found by HRID and deleted"
            body:
                application/json:
                    type: upsert-response-200
        400:
            description: "Bad request, for example: non-JSON in request body; inventory record set without an Instance"
            body:
                application/json:
                    type: error-response
        404:
            description: "Did not find existing Instance (record set) to delete for provided HRID "
            body:
                application/json:
                    type: error-response
        422:
            description: "One or more validation errors encountered. No deletion performed."
            body:
                application/json:
                    type: error-response
        500:
            description: "Internal error in the module or in storage during delete by HRID"
            body:
                application/json:
                    type: error-response

/inventory-batch-upsert-hrid:
  displayName: Create or update a batch of instances with holdings and items, based on incoming HRIDs on all three record types
  put:
    body:
        application/json:
            type: inventory-record-sets-with-hrids
    responses:
        200:
            description: "Batch of Inventory record sets successfully created or updated by HRIDs."
            body:
                application/json:
                    type: metrics
        207:
            description: "Partially successful update of record set. Errors enumerated in response."
            body:
                application/json:
                    type: batch-upsert-response-207
        400:
            description: "Bad request, for example: empty request body, non-JSON or invalid JSON in request body or JSON does not contain inventory record sets"
            body:
                application/json:
                    type: error-response
        422:
            description: "One or more validation errors found in incoming record set. No updates performed."
            body:
                application/json:
                    type: error-response
        500:
            description: "Internal error in the module or in storage during delete by HRID"
            body:
                application/json:
                    type: error-response


/inventory-upsert-hrid/fetch/{id}:
  displayName: Retrieve single Inventory record set either by Instance UUID or HRID
  get:
    responses:
       200:
         description: "Inventory record set found"
         body:
            application/json:
                type: get-recordset-response



/shared-inventory-upsert-matchkey:
  displayName: Create, update, "delete" instance, replace its holdings and items, based on instance match key
  put:
    body:
        application/json:
            type: inventory-record-set
    responses:
        200:
            description: "Inventory recordset successfully created or updated by match key"
            body:
                 application/json:
                   type: upsert-response-200
        207:
            description: "Partially successful update of record set. Errors listed in response."
            body:
                application/json
                    type: upsert-response-207
        400:
          description: "Bad request, for example: non-JSON in request body; inventory record set without an Instance."
          body:
            application/json:
              type: error-response
        422:
          description: "One or more validation errors encountered. No updates performed."
          body:
            application/json:
              type: error-response
        500:
            description: "Internal error in the module or in storage module."
            body:
                application/json:
                    type: error-response

  delete:
    body:
        application/json:
          type: shared-index-deletion
    responses:
        200:
            description: "Record set was successfully found by local ID and cleaned up."
            body:
                application/json:
                    type: upsert-response-200
        400:
            description: "Bad request, for example: non-JSON in request body."
            body:
                application/json:
                    type: error-response
        404:
            description: "Did not find existing Instance (record set) to clean up for given local ID."
            body:
                application/json:
                    type: error-response
        422:
            description: "One or more validation errors encountered. No deletion performed."
            body:
                application/json:
                    type: error-response
        500:
            description: "Internal error in the module or in storage during delete by local ID."
            body:
                application/json:
                    type: error-response

/shared-inventory-upsert-matchkey/fetch/{id}:
  displayName: Retrieve single Inventory record set either by Instance UUID or HRID
  get:
    responses:
       200:
         description: "Inventory record set found"
         body:
            application/json:
                type: get-recordset-response

/shared-inventory-batch-upsert-matchkey:
  displayName: Create or update a batch of instances with holdings and items, based on the match-key for the incoming Instance
  put:
    body:
        application/json:
            type: inventory-record-sets
    responses:
        200:
            description: "Batch of Inventory record sets successfully created or updated by match-key."
            body:
                application/json:
                    type: metrics
        207:
            description: "Partially successful update of record set. Errors enumerated in response."
            body:
                application/json:
                    type: batch-upsert-response-207
        400:
            description: "Bad request, for example: empty request body, non-JSON or invalid JSON in request body or JSON does not contain inventory record sets."
            body:
                application/json:
                    type: error-response
        422:
            description: "One or more problems encountered when creating/updating a batch of Inventory record sets by match-keys."
            body:
                application/json:
                    type: error-response
        500:
            description: "Internal error in the module or in the storage module."
            body:
                application/json:
                    type: error-response
